name: Control Push
on: push

# ① Définition globale : disponible partout
env:
  APP_ENV: developpement
  NON_SECRET_VAR: "hello-world"

jobs:
  qa:
    name: Check tests
    runs-on: ubuntu-22.04

    environment: developpement

    # ② Définition au niveau du job (fusionnée avec la globale)	
    env:
      MY_API_TOKEN: ${{ secrets.MY_API_TOKEN }}
      JOB_ONLY_VAR: "variable-de-job"			
    steps:
      - name: Checkout on master
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.x"

      - name: Install pytest and flake8
        run: |
          pip install pytest
          pip install flake8

      - name: Run tests
        run: |
          pytest

      - name: Run flake8
        uses: py-actions/flake8@v2
        continue-on-error: true

      - name: Illustration des variables
        run: |
          # Variables globales
          echo "APP_ENV = $APP_ENV"
          echo "NON_SECRET_VAR = $NON_SECRET_VAR"

          # Variables de job
          echo "JOB_ONLY_VAR = $JOB_ONLY_VAR"

          # Secret (masqué)
          echo "MY_API_TOKEN = $MY_API_TOKEN"	

