name: Control Push
on: push
jobs:
  qa:
    name: Check tests
    runs-on: ubuntu-22.04

    environment: developpement
    env:
      MY_API_TOKEN: ${{ secrets.MY_API_TOKEN }}			
    steps:
      - name: Checkout on master
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.x"

      - name: Install pytest and flake8
        run: |
          pip install pytest
          pip install flake8

      - name: Run tests
        run: |
          pytest

      - name: Run flake8
        uses: py-actions/flake8@v2

      - name: Illustration de l'utilisation du secret
        run: |
          # On affiche la variable : la vraie valeur restera masquée dans les logs
          echo "Le secret MY_API_TOKEN vaut : $MY_API_TOKEN"
